version: "2.6.0"
services:
  db:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zicky
      MONGO_INITDB_ROOT_PASSWORD: zicky
    ports:
      - "27017:27017"
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      MONGO_URL: "mongodb://zicky:zicky@db:27017/?authSource=admin"
    command: npm run dev
